# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# Steps
steps:


# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'

# Start the build process
- script: bash build.sh   $env:$(AZURE_VARIABLE)
  displayName: 'Run build script'
  
# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Vm-samar@104.211.5.33'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true


